### PR TITLE
Add velodrome and influxdb operators.

### PR DESCRIPTION
**Pull request by jbarrick-mesosphere**
Velodrome is a service for collecting metrics about Github projects and Prow used for the Kubernetes test-infra: https://github.com/kubernetes/test-infra/tree/master/velodrome

We will use this operator in our KUDO Prow instance as well as elsewhere.

Velodrome depends on influxdb, so this also adds an influxdb operator.

Also adds tests and adds a `DATABASE` setting to MySQL that can be used to affect the database name used by MySQL.

### CODE REVIEW

**Comment by jbarrick-mesosphere** [comment]
/cc @zmalik @alenkacz @kensipe @gerred 

I'm still working on this as I need to add more docs, settings, and have some tests to fix.. but it would be nice to get some eyes on it as it is near complete.

**Comment by jbarrick-mesosphere** [comment]
https://00e9e64bac92a5cd005b2505a9057452e34f98454fa5a4beb8-apidata.googleusercontent.com/download/storage/v1/b/kudo-prow-logs/o/pr-logs%2Fpull%2Foperators%2F66%2Ftest-kubernetes-1.12%2F1161016055523446785%2Fartifacts%2Fkind-logs-1565643505%2Fkind-control-plane%2Fcontainers%2Fmysql-install-deploy-job-z2j4b_kudo-test-tolerant-shrew_deploy-7660da746c595b0b39519bc5d7b40f5c23b12d8d77b54c1ad67e04e133f86834.log?qk=AD5uMEsOHxcv-H6iHwQY1HGbaTkLoY5zsnZJP1Bxlnr1z2IBnVyi7F6f9smMYOiZ_o2XYp7ychPzVDaArfPhMLybBr08iUQE8HLQgMWnThyA7-X5F9VOuoPJoFCIpQ5-M_mFBm2jpMRps46-c2sOe4UmTMrMfKfsEH4KjzfnFjhZkWACIWzu7PdFqMrUAzDwXhm2DiQjLXIu3h-u-cdtxbIQQnZ3XsS7FFjG4_kZEkdCefS6eBn7DTS7Id1EyJ17R6B3WhoSDZH4f8EGprAiZCDoZHnWtRD-NRTgzqv3T_NKJErFH121pkDEMUN8G5S0pfaweVMuKAlVF8LUvMf54LlT5Qya3x9gASDMtgLeZHgzzStsnMCTv7petDt66uPZhFrRSUtQhuetGwwVg2i4MkSfakrI8d72-Uc8E52RErUcPb7tUq3Td1iEwyKM9wnOWs-A9gjhJZd6HqbFK4UR8HxYSfbOOX4q3igefWd463VhHg4nzk71y3fdYOZXDLECIJY3GE4oqqSlS7xi4Nw2lcSHkcHESpnNCmfTrhbgxNpFpiPo_Jz3LFFfH_36ooU0ekmABtqK_NeG02NBznoz_RDNLyjVtU6PkBomclE_9KqiHawd0NG2wvz4nQNxqE0ZQHEgFzw4sLH5H3GxSV0NT7Dv4Cjn-mug0IAZolj50GmvdHNdHXrQw2-Z5VGt8tGJOGvSw0M11RF9mA2zexdgE1Z7MuF4Y79KR8jRZqN7zEmSwxBUsX92cdPlQ-Z9ps9vxLUrOwvWS6ItJyKtifPPt76ZVz7sXBLnmtgVKQ9CoIn_NhJekMGqdlpCGuZq4rGpCRHMpod_9jezm1ufhH15d7jydA7JvL9YpQ8Ghl4DThtp_c5OXFuC7DERuwwUP2k9sYw294PBY5QMqvHfyDVHnV3q7XekZKSLuCK84NE6umrE7TkfnQrwAfWP66_sSWJDgnbdQPHY2BDEfy_fBzijYD5lGKEtHFmFhPtKC7sf5AkRbmA7ErZehetF-BsRvGoLKvTDvTq2qvwFisyCC-s8E4bl15eSeUAzXZDdwp8YZ9jM59xCXIwKj3-aVZQ8OIs_1lxRpoDSi1X5tQiji03R23HRwb0FL8JOJ-PjXCo3vfcpy_WKJjQg8pc

Looks like an idempotence issue in the mysql operator:

> 2019-08-12T20:56:37.71987239Z stderr F ERROR 1050 (42S01) at line 1: Table 'example' already exists

@gerred are we trying to have any kind of "at-most-once" guarantees in tasks? Or should tasks be idempotent?

**Comment by alenkacz** [comment]
@jbarrick-mesosphere what you're submitting in a task is a job, that job can be restarted based on the policy provided. Kudo should not create multiple jobs on one plan execution, that would be a bug.

**Review by gerred — APPROVED** [review]

**Comment by kensipe** [comment]
@jbarrick-mesosphere what's the status here?

**Review by fabianbaier — CHANGES_REQUESTED** [review]
needs a rebase but other than that lgtm

**Pull request closed without merging**
