### PR TITLE
elastic: make StorageClass configurable

### LINKED ISSUE #258: Specify StorageClass parameter while deploying Elastic Operator
While installing kudo based Operator for Elastic, it should have the provision to change the StorageClass. In my GKE deployment, it used `standard` StorageClass. Ideally, this parameter should be configurable which is already done for other Kudo based operator such as Kafka.

### PR DESCRIPTION
**Pull request by rishabh96b**
Resolves #258 

Signed-off-by: Rishabh Bohra rishabhbohra01@gmail.com

### CODE REVIEW

**Review by zmalik — APPROVED** [review]
LGTM

**Comment by zmalik** [comment]
@rishabh96b can you bump the operatorVersion to `0.2.2`?

**Review by nfnt — APPROVED** [review]
LGTM, but please bump the operator version as @zmalik suggested.

**Comment by rishabh96b** [comment]
Thanks for the approvals @zmalik and @nfnt . I have bumped the `operatorVersion` to `0.2.2`

**Pull request merged**
