### PR TITLE
Add basic MariaDB operator

### PR DESCRIPTION
**Pull request by yankcrime**
This is little more than a search-and-replace of the existing MySQL operator, but going forward I think this one should be used instead.

### CODE REVIEW

**Comment by yankcrime** [comment]
I've not added it to the README or the tests yet, if folks think that this is a good idea then I'll do that.

**Comment by jbarrick-mesosphere** [comment]
I actually have a bunch of changes and tests added to the MySQL operator in https://github.com/kudobuilder/operators/pull/66. I wonder if it would be a good idea to try to do this after that? I guess this will continue to be a problem as changes are made to the operators so maybe I should just get used to backporting.

Or maybe extensions can help with that problem? :thinking:

**Comment by jbarrick-mesosphere** [comment]
/approve

(also go ahead and add this to kudo-test.yaml, even without any tests added the operator will still be installed)

**Comment by yankcrime** [comment]
Oh nice, thanks @jbarrick-mesosphere.  I'll hold this for now and rebase once your PR has been merged and I can then incorporate your stuff as well.

**Comment by yankcrime** [comment]
Closing as this needs refactoring against a newer version of KUDO.

**Pull request closed without merging**
